import React from 'react'
import styles from './page6.module.scss'

const Page6 = () => {
  return (
    <div className={styles.wrapper}>
    <h5><p>With the rise and spread of ad targeted hyper networks of mass persuasion and misinformation, these new money, mad king, tech behemoth, monopolisers of capital, time and attention have re-enshrined the near ancient selfish secrecy of those who understand the art yet believe nothing should be revealed––condemning us all to the loss of know-how and destruction of all the wealth that could have been. 
<br></br><br></br>
The counterparty action starts with gathering the components that make primary production uncensorable. 
<br></br><br></br>
The first of these is entirely familiar to every generation born yesterday or a century ago. Relatively new yet quickly interwoven into every serious practice of society, economics, work and play, what we call social media is really a small collection of a few essential features across a handful of distinguishable channels. They each emphasise a distinct aspect of user content and interactions, with the most notable of them including video uploads & streaming of practically any length, topic or purpose, quick sometimes threaded bursts of micro posts that can be photos, text, images, polls or short videos, algorithmically fed to you short clips quickly edited, filtered and overlaid with music, and, IRC meets voiceover IP with a fresh coat of paint. The features they have in common are practically invisible to us all by now, from profile photos and user accounts to upvotes, downvotes, private messages, reposts, follows and blocks.
<br></br><br></br>
These are all fully understood, easily replicable mass scale responsive interfaces built on branded social graphs. 
<br></br><br></br>
These social graphs begin to deliver on what makes the free flow of endlessly original content and personal coordination between friends and strangers alike so damn powerful. They begin, but for the lack of personal sovereignty, quickly fail to prevent misinformation, polarization, and attacks against our ever more valuable private data from letting all users down hard.
<br></br><br></br>
It isn’t until community governance, shared ownership and dispute resolution are rooted in a manifest stake for each participant across all cultures and societies that social graphs actually deliver. 
<br></br><br></br>
The unexpected benefits that make graphs, owned and operated through decentralised social coordination, and enshrined item by item, choice by choice within instant cultural delivery mechanisms, which we have come to call NFTs, just hit different.
<br></br><br></br>
Independent from anyone who would normally try, given any chance, to cut you off from your rights to stake, strike, create, vote and govern, and freely associate with whoever you please,  there are a surprisingly small number of mechanisms that make DAOs, NFTs, and really anything in web3, work so much better than any of the previous attempts that have come before. They are at a minimum; the ability to mint, transfer, add a primary sale price, set a token URI, burn, stake and add a relationship. 
<br></br><br></br>
Systems collapse when the yield stress of the carrying capacity within an ecosystem is breached. These convex flares snap to produce market crashes and a perpetual generation of Halting errors. The only counter to disentangle this tug of war is through a factorial decentralisation of the capital stack, where diverse pools of capital supply are able to provide frictionless entry, strike, swap, and aggregate discovery to prevent outsized capital flow distortions and disincentives. 
<br></br><br></br>
How does real capital make itself available with the ability to move from the places where it gathers to places where it is useful in real time continuously, whilst actively preventing and incentivising against tyrannies of the minority, the majority and malicious actions generated by tugs of war between both extremes?</p></h5>
  </div> 
  )
}

export default Page6